[package]
name = "passwd_gen"
version = "0.1.0"
authors = ["John Hight <john@hight.net>"]
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arboard = "2.0"
rand = "0.8"
clap = "3.0"
